### ISSUE TITLE
Implement Infinite Scroll for Image Gallery

### ISSUE THREAD

**Issue by vvs-basanth** [g-aeroastro-c/gitam-aero.astro#53]
The image gallery needs to be enhanced with infinite scroll functionality. Currently, the gallery is limited in the text strings instead of images, which is not our goal. Implementing infinite scroll will allow users to continuously load and view more images as they scroll down the page.

**Steps to Reproduce:**
1. Visit the image gallery section of the site.
2. Scroll down to the bottom of the current image list.
3. Notice that no additional images are loaded beyond a certain point.

**Expected Behavior:**
The image gallery should seamlessly load more images without actually scrolling down or any kind of user behaviour, creating an infinite scroll effect. This should be smooth and without any significant delays.

**Actual Behavior:**
The gallery currently does not load additional images after a certain point, limiting the user's ability to view more content.

**Possible Causes:**
- Lack of infinite scroll implementation.
- Change in Props
- Issues with the front-end logic handling the infinite scroll.

**Suggested Fix:**
- Implement infinite scroll functionality using front-end technologies such as JavaScript or a library like React Infinite Scroll or Intersection Observer.
- Ensure the back-end API is properly configured to serve additional images as requested.
- Optimize loading performance to ensure smooth scrolling and quick image loading.
- Add a loading indicator or placeholder to inform users that more content is being fetched.

**Environment:**
- **Browser:** FireFox Developer Version
- **Platform:** Desktops - Web
- **Affected Pages:** See the attachments down below

**Attachments:**
![Image](https://github.com/user-attachments/assets/d671fb2b-292d-4ae3-b748-78acfedd4c64)

---

Let me know if you need further adjustments!

**Comment by IbrahimDev00** [comment]
@vvs-basanth Does this have to be horizontally infinite or vertically ? The issue suggests vertical infinite gallery.

**Comment by vvs-basanth** [comment]
> The issue suggests vertical infinite gallery.
It is Horizontally Infinite, will change that.
